### ISSUE TITLE
Your blog return 404.

### ISSUE THREAD

**Issue by psbss** [Takumon/blog#257]
ブログ (https://takumon.com/) にアクセスしたところ、ステータスコード404が戻ります。

**Comment by psbss** [comment]
<img width="998" alt="スクリーンショット 2020-08-27 15 31 27" src="https://user-images.githubusercontent.com/24839924/91400345-6d8f8d80-e87a-11ea-9d00-35640ac17a93.png">

**Comment by snoop2head** [comment]
Same here

**Comment by logan-anderson** [comment]
Same!

**Comment by Takumon** [comment]
404について教えていただきありがとうございます。
現在、私のNetlifyのアカウントは料金未納によりサスペンドされています。
2020年内にはこの問題を解決する予定です！

Thank you for sharing the information about 404!
Now my account of Netlify has been suspended for non-payment...
I gonna fix the problem until this year.

**Comment by Takumon** [comment]
先ほど未納分を精算し、[ブログ](https://takumon.com/)を再開しました！

I have just paid Netfily fee. Now you can access [my blog](https://takumon.com/)!
